services:
  foxglove-amd64:
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/foxglove:amd64-0.2.0
    container_name: foxglove
    build:
      context: .
      args: { ARCH: linux/amd64 }
    tty: true
    ports:
      - ${FOXGLOVE_PORT:-8080}:8080
    volumes:
      - foxglove-layouts:/src/layouts

  foxglove-arm64:
    image: cr.yandex/crp8hpfj5tuhlaodm4dl/foxglove:arm64-0.2.0
    container_name: foxglove
    build:
      context: .
      args: { ARCH: linux/arm64/v8 }
    tty: true
    ports:
      - ${FOXGLOVE_PORT:-8080}:8080
    volumes:
      - foxglove-layouts:/src/layouts

volumes:
  foxglove-layouts:
