version: "3.9"

services:
  foxglove:
    container_name: "${CONTAINER_NAME:-foxglove-${USER}}"
    image: registry.robotics-lab.ru/foxglove:0.2.0
    tty: true
    build:
      context: .
      tags:
          - "registry.robotics-lab.ru/foxglove:latest"
          - "registry.robotics-lab.ru/foxglove:0.2.0"
      x-bake:
        platforms: [linux/arm64, linux/amd64]
        cache-to: "type=registry,ref=registry.robotics-lab.ru/foxglove:cache,mode=max"
        cache-from: "type=registry,ref=registry.robotics-lab.ru/foxglove:cache"
    ports:
      - ${FOXGLOVE_PORT:-8080}:8080
    volumes:
      - foxglove-layouts:/src/layouts

volumes:
  foxglove-layouts:

networks:
  default:
    name: "${CONTAINER_NAME:-foxglove-${USER}}"
